# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review_by',
        ),
        migrations.AddField(
            model_name='book',
            name='review_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.User'),
        ),
    ]
