# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0002_auto_20190305_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='users.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='review_by',
        ),
        migrations.AddField(
            model_name='review',
            name='review_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='books.Book'),
        ),
    ]
