# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190305_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default='this is a review'),
            preserve_default=False,
        ),
    ]
