# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
